export const PRODUCTS = [
  {
    id: 1,
    image: "/images/product_1.png",
    title:
      "J.VER Women's Dress Shirts Solid Long Sleeve Stretch Wrinkle-Free With Yello",
    category: "Dresses",
    rating: 4.5,
    reviews: 2910,
    price: 900,
    originalPrice: 1300,
    discountBadge: "25% OFF",
    colors: ["#D29F92", "#1F2937", "#E5E7EB", "#D29F92", "#1F2937"],
  },
  {
    id: 2,
    image: "/images/product_2.png",
    title:
      "J.VER Women's Dress Shirts Solid Long Sleeve Stretch Wrinkle-Free With Yello",
    category: "Dresses",
    rating: 4.5,
    reviews: 2910,
    price: 900,
    originalPrice: 1300,
    discountBadge: "25% OFF",
    colors: ["#D29F92", "#1F2937", "#E5E7EB"],
  },
  {
    id: 3,
    image: "/images/product_3.png",
    title:
      "J.VER Women's Dress Shirts Solid Long Sleeve Stretch Wrinkle-Free With Yello",
    category: "Dresses",
    rating: 4.5,
    reviews: 2910,
    price: 900,
    originalPrice: 1300,
    discountBadge: "25% OFF",
    colors: ["#D29F92", "#1F2937", "#E5E7EB"],
  },
  {
    id: 4,
    image: "/images/product_4.png",
    title:
      "J.VER Women's Dress Shirts Solid Long Sleeve Stretch Wrinkle-Free With Yello",
    category: "Dresses",
    rating: 4.5,
    reviews: 2910,
    price: 900,
    originalPrice: 1300,
    discountBadge: "25% OFF",
    colors: ["#D29F92", "#1F2937", "#E5E7EB"],
  },
  {
    id: 5,
    image: "/images/product_1.png",
    title:
      "J.VER Women's Dress Shirts Solid Long Sleeve Stretch Wrinkle-Free With Yello",
    category: "Dresses",
    rating: 4.5,
    reviews: 2910,
    price: 900,
    originalPrice: 1300,
    discountBadge: "25% OFF",
    colors: ["#D29F92", "#1F2937", "#E5E7EB"],
  },
  {
    id: 6,
    image: "/images/product_2.png",
    title: "Casual Cotton T-Shirt",
    category: "T-Shirts",
    rating: 4.8,
    reviews: 120,
    price: 450,
    originalPrice: 600,
    discountBadge: "HOT",
    colors: ["#ffffff", "#000000", "#ff0000"],
  },
  {
    id: 7,
    image: "/images/product_3.png",
    title: "Classic Denim Jacket",
    category: "Jackets",
    rating: 4.7,
    reviews: 500,
    price: 1200,
    originalPrice: 1500,
    discountBadge: "10% OFF",
    colors: ["#1F2937", "#3B82F6"],
  },
  {
    id: 8,
    image: "/images/product_4.png",
    title: "Elegant Evening Gown",
    category: "Dresses",
    rating: 4.9,
    reviews: 85,
    price: 2500,
    originalPrice: 1500,
    discountBadge: "10% OFF",
    colors: ["#000000", "#D29F92"],
  },
  {
    id: 9,
    image: "/images/product_1.png",
    title: "Summer Floral Dress",
    category: "Dresses",
    rating: 4.6,
    reviews: 320,
    price: 800,
    originalPrice: 1000,
    discountBadge: "20% OFF",
    colors: ["#ffcc00", "#ff6699", "#ffffff"],
  },
  {
    id: 10,
    image: "/images/product_2.png",
    title: "Sporty Running Shoes",
    category: "Shoes",
    rating: 4.7,
    reviews: 1500,
    price: 1100,
    originalPrice: 1400,
    discountBadge: "SALE",
    colors: ["#000000", "#ffffff"],
  },
];

export const GALLERIES = [
  "/images/gallery_1.png",
  "/images/gallery_2.png",
  "/images/gallery_3.png",
  "/images/gallery_4.png",
];
